// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.module.user.domain;

import com.rickdane.springmodularizedproject.module.user.domain.AppuserDataOnDemand;
import com.rickdane.springmodularizedproject.module.user.domain.AppuserIntegrationTest;
import com.rickdane.springmodularizedproject.module.user.repository.AppuserRepository;
import com.rickdane.springmodularizedproject.module.user.service.AppuserService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppuserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppuserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppuserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppuserIntegrationTest: @Transactional;
    
    @Autowired
    private AppuserDataOnDemand AppuserIntegrationTest.dod;
    
    @Autowired
    AppuserService AppuserIntegrationTest.appuserService;
    
    @Autowired
    AppuserRepository AppuserIntegrationTest.appuserRepository;
    
    @Test
    public void AppuserIntegrationTest.testCountAllAppusers() {
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", dod.getRandomAppuser());
        long count = appuserService.countAllAppusers();
        Assert.assertTrue("Counter for 'Appuser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppuserIntegrationTest.testFindAppuser() {
        Appuser obj = dod.getRandomAppuser();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to provide an identifier", id);
        obj = appuserService.findAppuser(id);
        Assert.assertNotNull("Find method for 'Appuser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Appuser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppuserIntegrationTest.testFindAllAppusers() {
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", dod.getRandomAppuser());
        long count = appuserService.countAllAppusers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Appuser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Appuser> result = appuserService.findAllAppusers();
        Assert.assertNotNull("Find all method for 'Appuser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Appuser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppuserIntegrationTest.testFindAppuserEntries() {
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", dod.getRandomAppuser());
        long count = appuserService.countAllAppusers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Appuser> result = appuserService.findAppuserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Appuser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Appuser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppuserIntegrationTest.testFlush() {
        Appuser obj = dod.getRandomAppuser();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to provide an identifier", id);
        obj = appuserService.findAppuser(id);
        Assert.assertNotNull("Find method for 'Appuser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppuser(obj);
        Integer currentVersion = obj.getVersion();
        appuserRepository.flush();
        Assert.assertTrue("Version for 'Appuser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppuserIntegrationTest.testUpdateAppuserUpdate() {
        Appuser obj = dod.getRandomAppuser();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to provide an identifier", id);
        obj = appuserService.findAppuser(id);
        boolean modified =  dod.modifyAppuser(obj);
        Integer currentVersion = obj.getVersion();
        Appuser merged = appuserService.updateAppuser(obj);
        appuserRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Appuser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppuserIntegrationTest.testSaveAppuser() {
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", dod.getRandomAppuser());
        Appuser obj = dod.getNewTransientAppuser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Appuser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Appuser' identifier to be null", obj.getId());
        appuserService.saveAppuser(obj);
        appuserRepository.flush();
        Assert.assertNotNull("Expected 'Appuser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppuserIntegrationTest.testDeleteAppuser() {
        Appuser obj = dod.getRandomAppuser();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Appuser' failed to provide an identifier", id);
        obj = appuserService.findAppuser(id);
        appuserService.deleteAppuser(obj);
        appuserRepository.flush();
        Assert.assertNull("Failed to remove 'Appuser' with identifier '" + id + "'", appuserService.findAppuser(id));
    }
    
}
