// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.module.user.domain;

import com.rickdane.springmodularizedproject.module.user.domain.AppuserDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppuserDataOnDemand_Roo_Configurable {
    
    declare @type: AppuserDataOnDemand: @Configurable;
    
}
