// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.module.user.domain;

import com.rickdane.springmodularizedproject.module.user.domain.Appuser;
import com.rickdane.springmodularizedproject.module.user.domain.AppuserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AppuserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppuserDataOnDemand: @Component;
    
    private Random AppuserDataOnDemand.rnd = new SecureRandom();
    
    private List<Appuser> AppuserDataOnDemand.data;
    
    public Appuser AppuserDataOnDemand.getNewTransientAppuser(int index) {
        Appuser obj = new Appuser();
        setEnabled(obj, index);
        setPassword(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void AppuserDataOnDemand.setEnabled(Appuser obj, int index) {
        Boolean enabled = Boolean.TRUE;
        obj.setEnabled(enabled);
    }
    
    public void AppuserDataOnDemand.setPassword(Appuser obj, int index) {
        String password = "password_" + index;
        if (password.length() > 100) {
            password = password.substring(0, 100);
        }
        obj.setPassword(password);
    }
    
    public void AppuserDataOnDemand.setUsername(Appuser obj, int index) {
        String username = "username_" + index;
        if (username.length() > 100) {
            username = username.substring(0, 100);
        }
        obj.setUsername(username);
    }
    
    public Appuser AppuserDataOnDemand.getSpecificAppuser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Appuser obj = data.get(index);
        Long id = obj.getId();
        return Appuser.findAppuser(id);
    }
    
    public Appuser AppuserDataOnDemand.getRandomAppuser() {
        init();
        Appuser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Appuser.findAppuser(id);
    }
    
    public boolean AppuserDataOnDemand.modifyAppuser(Appuser obj) {
        return false;
    }
    
    public void AppuserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Appuser.findAppuserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Appuser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Appuser>();
        for (int i = 0; i < 10; i++) {
            Appuser obj = getNewTransientAppuser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
