// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rickdane.springmodularizedproject.module.consumabledata.domain;

import java.lang.String;

privileged aspect Datarecord_Roo_JavaBean {
    
    public String Datarecord.getEntry() {
        return this.entry;
    }
    
    public void Datarecord.setEntry(String entry) {
        this.entry = entry;
    }
    
}
